import test from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL,fileURLToPath} from 'node:url';
const root=process.env.CREATOR_CORE_DIR||fileURLToPath(new URL('../../../src/creator/core/',import.meta.url));
const c=await import(pathToFileURL(`${root}/core.mjs`));
const e=await import(pathToFileURL(`${root}/exchange.mjs`));
const s=await import(pathToFileURL(`${root}/store.mjs`));
function fixture(){let state=c.createWorkspace({id:'synthetic_source'}),i=0;const run=(type,payload)=>{const r=c.applyCommand(state,{type,payload,operationId:`op_${++i}`,expectedRevision:state.revision});state=r.state;return r.result;};const workId=run('captureIdea',{title:'Synthetic work',angle:'Synthetic angle',references:[{url:'https://example.com/source',analysis:'Synthetic analysis'}]}).workId,accountId=run('createAccount',{displayName:'Synthetic account',platform:'test'}).accountId;run('startProduction',{workId});run('saveDraft',{workId,body:'Synthetic draft'});run('addAsset',{workId,name:'synthetic-video.mp4',mimeType:'video/mp4',size:2048});run('setSchedule',{workId,accountId,schedule:{date:'2026-10-07',timeZone:'UTC',allDay:true}});return state}
async function rehash(pkg){for(const r of pkg.records)r.hash=await e.sha256(c.canonical(r.entity));pkg.relations=pkg.records.flatMap(r=>e.relationsFor(r.collection,r.id,r.entity)).sort((a,b)=>c.canonical(a).localeCompare(c.canonical(b)));delete pkg.packageHash;pkg.packageHash=await e.sha256(c.canonical(pkg));return pkg}
test('every default origin is synthetic and shared github.io refuses private override',()=>{for(const origin of ['','null','https://1337816143.github.io','https://preview.example.com','http://localhost:8000','file:///tmp/index.html']){assert.equal(s.storagePolicy({origin}).mode,'demo');assert.equal(s.storagePolicy({origin}).allowBackupImport,false)}assert.equal(s.storagePolicy({origin:'https://1337816143.github.io',approvedPrivateOrigin:true}).allowBackupImport,false)});
test('valid backup fresh in-memory restore keeps IDs, references, drafts and missing asset truth',async()=>{const source=fixture(),pkg=await e.exportPackage(source),target=s.createMemoryStore({initialState:c.createWorkspace({id:'synthetic_target'})});const preview=await target.previewImport(pkg);assert.equal(preview.missingAssets.length,1);assert.equal(pkg.assetManifest[0].included,false);assert.equal(pkg.assetManifest[0].bytesVerified,false);await target.importPackage(pkg,{operationId:'import_1',expectedRevision:0});const imported=await target.read();for(const col of c.COLLECTIONS)assert.deepEqual(imported[col],source[col]);assert.equal((await target.listRestorePoints()).length,1);target.close()});
test('missing mandatory ownership is rejected even when package hashes and relations are valid',async()=>{for(const col of ['references','drafts','tasks','publications','assets']){const pkg=await e.exportPackage(fixture());const record=pkg.records.find(r=>r.collection===col);delete record.entity.workId;await rehash(pkg);await assert.rejects(e.validatePackage(pkg),undefined,`${col} with absent workId must be rejected`)}const pkg=await e.exportPackage(fixture());delete pkg.records.find(r=>r.collection==='publications').entity.accountId;await rehash(pkg);await assert.rejects(e.validatePackage(pkg))});
test('hash, unsafe URL and unsafe asset path reject without relying on caller',async()=>{let pkg=await e.exportPackage(fixture());pkg.records[0].entity.title='Modified';await assert.rejects(e.validatePackage(pkg),x=>x.code==='BAD_HASH');pkg=await e.exportPackage(fixture());pkg.records.find(r=>r.collection==='references').entity.url='javascript:alert(1)';await rehash(pkg);await assert.rejects(e.validatePackage(pkg),x=>x.code==='UNSAFE_URL');pkg=await e.exportPackage(fixture());const asset=pkg.records.find(r=>r.collection==='assets').entity;asset.name='../private.mp4';pkg.assetManifest[0].name=asset.name;await rehash(pkg);await assert.rejects(e.validatePackage(pkg),x=>x.code==='UNSAFE_PATH')});
test('failed atomic memory import leaves no state, notification or restore point; successful restore is recoverable',async()=>{const source=fixture(),pkg=await e.exportPackage(source),initial=c.createWorkspace({id:'synthetic_target'});let fail=true,notifications=0;const target=s.createMemoryStore({initialState:initial,failWrite:({kind})=>{if(fail&&kind==='import')throw Object.assign(new Error('synthetic quota'),{name:'QuotaExceededError'})}});target.subscribe(()=>notifications++);await assert.rejects(target.importPackage(pkg,{operationId:'import_1',expectedRevision:0}),x=>x.code==='STORAGE_QUOTA');assert.deepEqual(await target.read(),initial);assert.equal((await target.listRestorePoints()).length,0);assert.equal(notifications,0);fail=false;const result=await target.importPackage(pkg,{operationId:'import_1',expectedRevision:0});assert.equal(notifications,1);const beforeRestore=await target.read();const restored=await target.restore({operationId:'restore_1',expectedRevision:beforeRestore.revision,restorePointId:result.result.restorePointId});for(const col of c.COLLECTIONS)assert.deepEqual(restored.state[col],initial[col]);assert.equal((await target.listRestorePoints()).length,2);const redo=await target.restore({operationId:'restore_2',expectedRevision:restored.state.revision,restorePointId:restored.result.restorePointId});for(const col of c.COLLECTIONS)assert.deepEqual(redo.state[col],beforeRestore[col]);target.close()});
test('same import is idempotent and changed same package ID is rejected',async()=>{const pkg=await e.exportPackage(fixture()),target=s.createMemoryStore();let state=await target.read();await target.importPackage(pkg,{operationId:'import_1',expectedRevision:state.revision});state=await target.read();const again=await target.importPackage(pkg,{operationId:'import_2',expectedRevision:state.revision});assert.equal(again.replayed,true);assert.equal((await target.read()).revision,state.revision);const changed=c.clone(pkg);changed.generatedAt='2026-10-04T00:00:00Z';await rehash(changed);await assert.rejects(target.previewImport(changed),x=>x.code==='PACKAGE_ID_REUSED');target.close()});
test('concurrent writes with identical expected revision accept one and preserve the committed side',async()=>{const target=s.createMemoryStore(),initial=await target.read();const results=await Promise.allSettled([target.dispatch({type:'createAccount',operationId:'first',expectedRevision:initial.revision,payload:{displayName:'Synthetic A',platform:'test'}}),target.dispatch({type:'createAccount',operationId:'second',expectedRevision:initial.revision,payload:{displayName:'Synthetic B',platform:'test'}})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'STALE_REVISION');assert.equal(Object.keys((await target.read()).accounts).length,1);target.close()});
function publishedFixture(){let state=fixture(),serial=100;const run=(type,payload)=>{const r=c.applyCommand(state,{type,payload,operationId:`op_${++serial}`,expectedRevision:state.revision});state=r.state;return r.result};const w=Object.values(state.works)[0],p=Object.values(state.publications)[0];for(const t of Object.values(state.tasks))run('setTaskState',{workId:w.id,taskId:t.id,status:'done'});run('setReady',{workId:w.id});run('recordPublication',{workId:w.id,accountId:p.accountId,publicationId:p.id,actualPublishedAt:'2026-10-05T00:00:00Z',publicUrl:'https://example.com/synthetic'});const other=run('captureIdea',{title:'Synthetic second work',angle:'Second synthetic angle'}).workId;run('startProduction',{workId:other});run('saveDraft',{workId:other,body:'Other synthetic draft'});return state}
test('declared published package requires complete nonempty final snapshot',async()=>{for(const finalSnapshot of [null,{}, {title:'Synthetic work',body:'',draftId:'missing',assetIds:[]}]){const pkg=await e.exportPackage(publishedFixture());pkg.records.find(r=>r.collection==='publications').entity.finalSnapshot=finalSnapshot;await rehash(pkg);await assert.rejects(e.validatePackage(pkg))}});
test('cross-work draft/publication ownership rejects valid-hash imports atomically',async()=>{const source=publishedFixture(),works=Object.values(source.works),first=works[0],other=works[1],otherDraft=source.drafts[other.bodyRevisionId];for(const mismatch of ['current-draft','final-draft']){const pkg=await e.exportPackage(source);if(mismatch==='current-draft')pkg.records.find(r=>r.id===first.id).entity.bodyRevisionId=otherDraft.id;else{const p=pkg.records.find(r=>r.collection==='publications').entity;p.finalRevisionId=otherDraft.id;p.finalSnapshot={title:otherDraft.title,body:otherDraft.body,draftId:otherDraft.id,assetIds:[]}}await rehash(pkg);const target=s.createMemoryStore();const before=await target.read();await assert.rejects(target.importPackage(pkg,{operationId:'mismatch',expectedRevision:before.revision}),x=>x.code==='RELATION_MISMATCH');assert.deepEqual(await target.read(),before);assert.equal((await target.listRestorePoints()).length,0);target.close()}});
test('incoming conflict choice never replaces immutable draft, metric, or published fact IDs',async()=>{for(const kind of ['drafts','metrics','publications']){let source=kind==='publications'?publishedFixture():fixture();if(kind==='metrics'){const accountId=Object.keys(source.accounts)[0];source=c.applyCommand(source,{type:'appendMetrics',operationId:'metric_seed',expectedRevision:source.revision,payload:{snapshots:[{accountId,metricKey:'followers',value:100,observedAt:'2026-10-05T00:00:00Z'}]}}).state}const pkg=await e.exportPackage(source);const record=pkg.records.find(r=>r.collection===kind);if(kind==='drafts')record.entity.body='Divergent synthetic draft';if(kind==='metrics')record.entity.value=999;if(kind==='publications')record.entity.actualPublishedAt='2026-10-06T00:00:00Z';await rehash(pkg);const target=s.createMemoryStore({initialState:source}),before=await target.read();const preview=await target.previewImport(pkg);assert(preview.conflicts.some(x=>x.key===`${kind}:${record.id}`));const choices=Object.fromEntries(preview.conflicts.map(x=>[x.key,'incoming']));await assert.rejects(target.importPackage(pkg,{operationId:`replace_${kind}`,expectedRevision:before.revision,choices}),x=>x.code==='IMMUTABLE_CONFLICT');assert.deepEqual(await target.read(),before);assert.equal((await target.listRestorePoints()).length,0);target.close()}});
test('archived import cannot smuggle an invalid ready phase through restore',async()=>{const pkg=await e.exportPackage(fixture());const work=pkg.records.find(r=>r.collection==='works').entity;work.phase='archived';work.previousPhase='ready';await rehash(pkg);await assert.rejects(e.validatePackage(pkg),x=>['INVALID_READY_STATE','INVALID_TASK_TEMPLATE'].includes(x.code))});
