import test from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL,fileURLToPath} from 'node:url';
const c=await import(pathToFileURL(process.env.CREATOR_CORE_PATH||fileURLToPath(new URL('../../../src/creator/core/core.mjs',import.meta.url))));
function harness(){let state=c.createWorkspace({id:'review_workspace',now:'2026-10-01T00:00:00Z'}),serial=0;return {get state(){return state},dispatch(type,payload,now='2026-10-05T00:00:00Z',operationId=`review_${++serial}`){const r=c.applyCommand(state,{type,payload,expectedRevision:state.revision,operationId},{now});state=r.state;return r},set(s){state=s}}}
function ready(h){const workId=h.dispatch('captureIdea',{title:'Synthetic review work',angle:'Synthetic angle',contentType:'text'}).result.workId;const result=h.dispatch('startProduction',{workId}).result;h.dispatch('saveDraft',{workId,body:'Synthetic draft body'});for(const taskId of result.taskIds)h.dispatch('setTaskState',{workId,taskId,status:'done'});h.dispatch('setReady',{workId});return workId}
function account(h,platform='test'){return h.dispatch('createAccount',{displayName:`Synthetic ${platform}`,platform}).result.accountId}
function publish(h,workId,accountId,time='2026-10-05T08:00:00+08:00'){return h.dispatch('recordPublication',{workId,accountId,actualPublishedAt:time,publicUrl:'https://example.com/synthetic'}).result.publicationId}
test('same work and immutable final draft across two accounts and later revisions',()=>{const h=harness(),workId=ready(h),a=account(h),b=account(h,'other'),p1=publish(h,workId,a),p2=publish(h,workId,b);const old=h.state.publications[p1].finalSnapshot.body;h.dispatch('saveDraft',{workId,body:'Synthetic new draft'});assert.equal(h.state.publications[p1].finalSnapshot.body,old);assert.equal(h.state.publications[p2].workId,workId);assert.equal(c.selectWorkspace(h.state).totals.publishedWorks,1);assert.equal(c.selectWorkspace(h.state).totals.publications,2);assert.equal(c.selectWorkspace(h.state,{accountId:a}).publications.length,1)});
test('cumulative metrics latest/null/zero and equivalent-instant conflicts',()=>{const h=harness(),a=account(h);const snap=(value,observedAt)=>({accountId:a,metricKey:'followers',value,observedAt});h.dispatch('appendMetrics',{snapshots:[snap(100,'2026-10-01T00:00:00Z'),snap(160,'2026-10-02T00:00:00Z')]});assert.equal(c.latestMetrics(h.state,{accountId:a})[0].value,160);assert.equal(c.metricDelta(h.state,{accountId:a,metricKey:'followers'}).value,60);assert.throws(()=>h.dispatch('appendMetrics',{snapshots:[snap(161,'2026-10-02T08:00:00+08:00')]}),e=>e.code==='METRIC_CONFLICT');h.dispatch('appendMetrics',{snapshots:[snap(null,'2026-10-03T00:00:00Z')]});assert.equal(c.latestMetrics(h.state,{accountId:a})[0].value,null);assert.equal(c.metricDelta(h.state,{accountId:a,metricKey:'followers'}).value,null);h.dispatch('appendMetrics',{snapshots:[snap(0,'2026-10-04T00:00:00Z')]});assert.equal(c.latestMetrics(h.state,{accountId:a})[0].value,0)});
test('schedule all-day cancellation and undo preserve work/draft identities',()=>{const h=harness(),workId=ready(h),a=account(h),draft=h.state.works[workId].bodyRevisionId;const set=h.dispatch('setSchedule',{workId,accountId:a,schedule:{date:'2026-10-06',timeZone:'Asia/Shanghai',allDay:true}});const publicationId=set.result.publicationId;assert.equal(h.state.publications[publicationId].schedule.plannedAt,null);const cancelled=h.dispatch('cancelSchedule',{publicationId});assert(c.selectWorkspace(h.state).unscheduled.some(w=>w.id===workId));h.dispatch('undo',{targetOperationId:cancelled.result.undoOperationId});assert.equal(h.state.publications[publicationId].schedule.date,'2026-10-06');assert.equal(h.state.works[workId].bodyRevisionId,draft);assert.equal(c.selectWorkspace(h.state).totals.publications,0)});
test('DST gap rejects and fold requires explicit correct offset',()=>{assert.throws(()=>c.resolveSchedule({date:'2026-03-08',time:'02:30',timeZone:'America/New_York',allDay:false}),e=>e.code==='NONEXISTENT_LOCAL_TIME');assert.throws(()=>c.resolveSchedule({date:'2026-11-01',time:'01:30',timeZone:'America/New_York',allDay:false}),e=>e.code==='AMBIGUOUS_LOCAL_TIME');const a=c.resolveSchedule({date:'2026-11-01',time:'01:30',timeZone:'America/New_York',allDay:false,offsetMinutes:-240}),b=c.resolveSchedule({date:'2026-11-01',time:'01:30',timeZone:'America/New_York',allDay:false,offsetMinutes:-300});assert.equal(Date.parse(b.plannedAt)-Date.parse(a.plannedAt),3600000)});
test('idempotent command retries are permitted and stale/new or changed retry reject',()=>{const h=harness();const cmd={type:'createAccount',payload:{displayName:'Synthetic account',platform:'test'},expectedRevision:0,operationId:'fixed_operation'};const first=c.applyCommand(h.state,cmd);const repeat=c.applyCommand(first.state,cmd);assert.equal(repeat.replayed,true);assert.equal(Object.keys(repeat.state.accounts).length,1);assert.throws(()=>c.applyCommand(first.state,{...cmd,operationId:'new_operation'}),e=>e.code==='STALE_REVISION');assert.throws(()=>c.applyCommand(first.state,{...cmd,payload:{displayName:'Different account',platform:'test'}}),e=>e.code==='OPERATION_ID_REUSED')});
test('trash/restore keeps draft and published fact, archive restores original phase',()=>{const h=harness(),workId=ready(h),a=account(h),publicationId=publish(h,workId,a),draft=h.state.works[workId].bodyRevisionId;h.dispatch('trashWork',{workId});assert(h.state.works[workId].trashedAt);h.dispatch('restoreWork',{workId});assert.equal(h.state.works[workId].phase,'ready');assert.equal(h.state.works[workId].bodyRevisionId,draft);assert.equal(h.state.publications[publicationId].status,'published');h.dispatch('archiveWork',{workId});h.dispatch('restoreWork',{workId});assert.equal(h.state.works[workId].phase,'ready')});
test('goal month uses declared timezone and platform scoped views exclude other-account goals',()=>{const h=harness(),workId=ready(h),a=account(h,'A'),b=account(h,'B');publish(h,workId,a,'2026-10-01T00:30:00+08:00');const ga=h.dispatch('setGoal',{month:'2026-10',timeZone:'Asia/Shanghai',metric:'publications',target:2,accountId:a}).result.goalId;const gb=h.dispatch('setGoal',{month:'2026-10',timeZone:'Asia/Shanghai',metric:'publications',target:2,accountId:b}).result.goalId;assert.equal(c.selectWorkspace(h.state,{month:'2026-10'}).goals.find(g=>g.id===ga).actual,1);assert(!c.selectWorkspace(h.state,{month:'2026-10',platform:'A'}).goals.some(g=>g.id===gb))});
test('inherited object property names cannot masquerade as existing accounts',()=>{for(const accountId of ['toString','valueOf','hasOwnProperty']){const h=harness();assert.throws(()=>h.dispatch('appendMetrics',{snapshots:[{accountId,metricKey:'followers',value:999,observedAt:'2026-10-05T00:00:00Z'}]}),e=>e.code==='NOT_FOUND');assert.equal(Object.keys(h.state.metrics).length,0)}});
test('calendar-overflow timestamps reject rather than normalize in metric and publication facts',()=>{const h=harness(),accountId=account(h),workId=ready(h);for(const stamp of ['2026-02-30T00:00:00Z','2026-04-31T08:00:00+08:00','2026-02-29T00:00:00Z']){assert.throws(()=>h.dispatch('appendMetrics',{snapshots:[{accountId,metricKey:'followers',value:1,observedAt:stamp}]}),e=>e.code==='INVALID_DATE');assert.throws(()=>h.dispatch('recordPublication',{workId,accountId,actualPublishedAt:stamp,publicUrl:'https://example.com/synthetic'}),e=>e.code==='INVALID_DATE')}assert.equal(Object.keys(h.state.publications).length,0);assert.equal(Object.keys(h.state.metrics).length,0)});
