/* Real local Chrome + built-in Node CDP client; no package install or external service. */
const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output','navigation-review');fs.mkdirSync(out,{recursive:true});
const chrome=process.env.CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-extensions','--no-first-run','--remote-debugging-address=127.0.0.1','--remote-debugging-port=9251',`--user-data-dir=${path.join(out,'cdp-profile-'+Date.now())}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let ws,seq=0;const pending=new Map();
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
async function connect(){for(let i=0;i<100;i++){try{const targets=await(await fetch('http://127.0.0.1:9251/json/list')).json();const target=targets.find(t=>t.type==='page');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});ws.onmessage=event=>{const m=JSON.parse(event.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}};return;}catch(err){await sleep(100);}}throw Error('Local Chrome CDP unavailable');}
async function navigate(hash){await send('Page.navigate',{url:pathToFileURL(path.join(root,'dist/dashboard/index.html')).href+'?viewport='+Date.now()+'#'+hash});await sleep(150);for(let i=0;i<100;i++){if(await evaluate("document.readyState==='complete' && !!document.getElementById('result-count')?.textContent"))return;await sleep(30);}throw Error('Dashboard initialization timed out');}
(async()=>{try{await connect();await send('Page.enable');const results=[];
for(const width of [320,390,768,1280])for(const [layout,color] of [['B','dark'],['B','light'],['A','light']])for(const view of ['workbench','overview','library','tasks']){
await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<700});await navigate(view);await evaluate(`localStorage.setItem('mydotwork-appearance',JSON.stringify({layout:'${layout}',color:'${color}'}))`);await navigate(view);await evaluate('window.scrollTo(0,0)');await sleep(80);
const o=await evaluate(`(()=>{const sidebar=document.querySelector('.sidebar'),mobile=innerWidth<=1050,labels=['工作台','成果资料','项目网站','任务进度','研究总览','供应对比','源头方案','账号问题','Claude指南','研究修正','来源索引'];if(document.documentElement.scrollWidth>document.documentElement.clientWidth)throw Error('Page overflow');const links=[...sidebar.querySelectorAll('nav a')];if(links.length!==labels.length||!links.every((a,i)=>a.textContent===labels[i]&&a.getAttribute('aria-label')===labels[i]))throw Error('Semantic navigation labels');if(mobile){if(sidebar.classList.contains('open')||getComputedStyle(sidebar).visibility!=='hidden')throw Error('Drawer default not closed');if(!document.querySelector('.nav-toggle').getClientRects().length)throw Error('Menu unavailable');}else{if(![...sidebar.querySelectorAll('.sidebar-group .nav-label')].every(n=>getComputedStyle(n).display!=='none'&&n.getClientRects().length))throw Error('Missing visible navigation groups');if(sidebar.getBoundingClientRect().width<224)throw Error('Unlabelled narrow default');if(!links.every(a=>{const n=a.querySelector('span');return getComputedStyle(n).display!=='none'&&n.scrollWidth<=n.clientWidth+1&&a.getBoundingClientRect().right<=sidebar.getBoundingClientRect().right;}))throw Error('Desktop label clipping');if(getComputedStyle(document.querySelector('.workspace-nav')).display!=='none'||getComputedStyle(document.querySelector('.module-nav')).display!=='none')throw Error('Duplicate desktop navigation');}
const first=document.querySelector('#${view}-results .catalog-card,#${view}-results .task-card'),rows=[...document.querySelectorAll('.evidence-row')];if(innerWidth===390&&first?.getBoundingClientRect().bottom>844)throw Error('First complete card not visible');if(innerWidth===390&&'${view}'==='overview'&&rows[1].getBoundingClientRect().bottom>844)throw Error('First two quotes not visible');
const rgb=s=>(s.match(/[0-9.]+/g)||[]).map(Number),l=c=>c.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0),samples=[];for(const n of [...document.querySelectorAll('.sidebar nav a,.sidebar .nav-label,.lede,.small-note,.catalog-summary,input[placeholder]')].filter(n=>n.getClientRects().length&&getComputedStyle(n).visibility!=='hidden')){const style=getComputedStyle(n,n.matches('input[placeholder]')?'::placeholder':null);let p=n,bg;while(p){bg=rgb(getComputedStyle(p).backgroundColor);if(bg.length<4||bg[3]>.99)break;p=p.parentElement;}if(!p)continue;const a=l(rgb(style.color)),b=l(bg),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);if(ratio<4.5)throw Error('Text contrast '+ratio+' '+n.textContent.slice(0,35));samples.push({type:n.matches('input')?'placeholder':'text',ratio});}
const catalog=JSON.parse(document.getElementById('catalog-data').textContent);if(catalog.counts.artifacts!==15||catalog.counts.websites!==4||catalog.counts.tasks!==17)throw Error('Published catalogue lost');return {width:innerWidth,layout:document.body.dataset.layout,color:document.body.dataset.color,view:'${view}',navWidth:sidebar.getBoundingClientRect().width,drawer:mobile,firstCardBottom:first?.getBoundingClientRect().bottom,secondQuoteBottom:'${view}'==='overview'?rows[1].getBoundingClientRect().bottom:null,contrast:samples,counts:catalog.counts};})()`);results.push(o);const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,`navigation-${layout}-${color}-${width}-${view}.png`),Buffer.from(shot.data,'base64'));
}
const key=async(k)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key:k,code:k,text:k==='Enter'?'\r':undefined,windowsVirtualKeyCode:k==='Tab'?9:k==='Escape'?27:13});await send('Input.dispatchKeyEvent',{type:'keyUp',key:k,code:k});await sleep(80);};
await send('Page.bringToFront');
for(const [layout,color] of [['B','dark'],['B','light'],['A','light']]){
await send('Emulation.setDeviceMetricsOverride',{width:1280,height:844,deviceScaleFactor:1,mobile:false});await evaluate(`localStorage.setItem('mydotwork-appearance',JSON.stringify({layout:'${layout}',color:'${color}'}))`);await navigate('quotes');await evaluate(`document.getElementById('q').value='ProPlus';document.getElementById('q').dispatchEvent(new Event('input'));document.getElementById('tier').value='Plus';document.getElementById('tier').dispatchEvent(new Event('change'));document.getElementById('sidebar-collapse').focus()`);const before=await evaluate(`document.getElementById('result-count').textContent`);assert(before.startsWith('1 条'),'Meaningful nonempty filter');await key('Enter');assert(await evaluate(`document.body.dataset.nav==='collapsed'&&document.getElementById('sidebar-collapse').getAttribute('aria-expanded')==='false'`),'Native collapse');assert.equal(await evaluate(`document.getElementById('result-count').textContent`),before,'Collapse keeps filters');await evaluate(`document.querySelector('[data-page="quotes"]').focus()`);assert(await evaluate(`!document.getElementById('navigation-tooltip').hidden&&document.getElementById('navigation-tooltip').textContent==='供应对比'`),'Focused collapsed tooltip');await evaluate('window.scrollTo(0,0)');const tip=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,`navigation-${layout}-${color}-1280-collapsed-tooltip.png`),Buffer.from(tip.data,'base64'));await key('Escape');assert(await evaluate(`document.getElementById('navigation-tooltip').hidden`),'Tooltip dismisses with Escape');await evaluate(`document.getElementById('sidebar-collapse').focus()`);await key('Enter');assert(await evaluate(`document.body.dataset.nav==='expanded'`),'Native expand');await evaluate(`document.querySelector('[data-page="quotes"]').focus()`);await evaluate('window.scrollTo(0,0)');const focus=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,`navigation-${layout}-${color}-1280-focus.png`),Buffer.from(focus.data,'base64'));
for(const width of [390,768]){await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<700});await navigate('overview');await evaluate(`document.querySelector('.nav-toggle').focus()`);await key('Enter');assert(await evaluate(`document.querySelector('.sidebar').classList.contains('open')`),'Native drawer opens');await key('Tab');assert(await evaluate(`document.querySelector('.sidebar').contains(document.activeElement)`),'Drawer traps focus');const menu=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,`navigation-${layout}-${color}-${width}-drawer.png`),Buffer.from(menu.data,'base64'));await key('Escape');assert(await evaluate(`!document.querySelector('.sidebar').classList.contains('open')&&document.activeElement.classList.contains('nav-toggle')`),'Drawer Escape restores focus');}
}
await send('Emulation.setDeviceMetricsOverride',{width:1280,height:844,deviceScaleFactor:1,mobile:false});await navigate('workbench');assert(await evaluate(`document.getElementById('hub-recent').textContent.includes('第3')&&document.getElementById('hub-recent').textContent.includes('低维护产品')&&document.getElementById('hub-tasks').textContent.includes('AI副业调研')`),'Both new report and project continuations');await evaluate(`document.querySelector('[data-task-id="project-17"]').click()`);await sleep(100);assert(await evaluate(`document.getElementById('tasks-task').value==='project-17'&&document.querySelectorAll('#tasks-results .task-card').length===1`),'Side-income continuation exact task');
await navigate('workbench');await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await sleep(100);assert(await evaluate(`document.documentElement.dataset.glass==='solid'`),'Reduced motion fallback');await send('Emulation.setEmulatedMedia',{features:[]});
await send('Emulation.setDeviceMetricsOverride',{width:375,height:812,deviceScaleFactor:1,mobile:true});await navigate('library');assert(await evaluate(`document.documentElement.scrollWidth<=document.documentElement.clientWidth`),'375px no overflow');await send('Emulation.setDeviceMetricsOverride',{width:844,height:390,deviceScaleFactor:1,mobile:true});await navigate('workbench');assert(await evaluate(`document.documentElement.scrollWidth<=document.documentElement.clientWidth&&!document.querySelector('.sidebar').classList.contains('open')`),'Landscape clear header/drawer');const landscape=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,'navigation-landscape-844x390.png'),Buffer.from(landscape.data,'base64'));
await send('Emulation.setDeviceMetricsOverride',{width:1280,height:844,deviceScaleFactor:1,mobile:false});await navigate('workbench');await evaluate(`(()=>{const style=document.createElement('style');style.textContent='body{font-size:20px}body[data-layout] .sidebar nav a{font-size:18px}.lede{font-size:18px}';document.head.append(style);})()`);assert(await evaluate(`[...document.querySelectorAll('.sidebar nav a span')].every(n=>n.scrollWidth<=n.clientWidth+1)`),'Large text labels fit');await evaluate('window.scrollTo(0,0)');const large=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,'navigation-large-text-stress-1280.png'),Buffer.from(large.data,'base64'));
results.push({status:'PASS',checks:['all published 14/4/17 preserved','native collapse/expand and focused full-name tooltip','filter state retained','default closed phone/tablet labelled drawer','native Tab/Escape focus','new round3-7 and side-income home links','exact project17 continuation','reduced motion','375px and 844x390 landscape','large-text navigation stress']});fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({status:'PASS',cases:48,first390:results.filter(x=>x.width===390).map(x=>({view:x.view,layout:x.layout,color:x.color,cardBottom:x.firstCardBottom,quoteBottom:x.secondQuoteBottom}))}));
}catch(e){console.error(e);process.exitCode=1;if(ws){try{const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,'navigation-failure.png'),Buffer.from(shot.data,'base64'));}catch{}}}finally{if(ws){try{await send('Browser.close');}catch{}ws.close();}child.kill();}})();
