/* Real local Chrome + built-in Node CDP client; no package install or external service. */
const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output','compact-review');fs.mkdirSync(out,{recursive:true});
const chrome=process.env.CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-extensions','--no-first-run','--remote-debugging-address=127.0.0.1','--remote-debugging-port=9233',`--user-data-dir=${path.join(out,'cdp-profile-'+Date.now())}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let ws,seq=0;const pending=new Map();
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
async function connect(){for(let i=0;i<100;i++){try{const targets=await(await fetch('http://127.0.0.1:9233/json/list')).json();const target=targets.find(t=>t.type==='page');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});ws.onmessage=event=>{const m=JSON.parse(event.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}};return;}catch(err){await sleep(100);}}throw Error('Local Chrome CDP unavailable');}
async function navigate(hash){await send('Page.navigate',{url:pathToFileURL(path.join(root,'dist/dashboard/index.html')).href+'?viewport='+Date.now()+'#'+hash});await sleep(150);for(let i=0;i<100;i++){if(await evaluate("document.readyState==='complete' && !!document.getElementById('result-count')?.textContent"))return;await sleep(30);}throw Error('Dashboard initialization timed out');}
(async()=>{try{
await connect();await send('Page.enable');const results=[];
for(const width of [320,390,768,1280])for(const [layout,color] of [['B','dark'],['B','light'],['A','light']])for(const hash of ['overview','library','tasks','workbench']){
await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<700});await navigate(hash);await evaluate(`localStorage.setItem('mydotwork-appearance',JSON.stringify({layout:'${layout}',color:'${color}'}))`);await navigate(hash);await sleep(100);await evaluate('window.scrollTo(0,0)');
const observation=await evaluate(`(()=>{const mobile=innerWidth<700,first=document.querySelector('#${hash}-results .catalog-card,#${hash}-results .task-card'),rows=[...document.querySelectorAll('.evidence-row')];if(document.documentElement.scrollWidth>innerWidth)throw Error('Page overflow');if(mobile&&document.querySelector('.sidebar').classList.contains('open'))throw Error('Menu initially open');if(mobile&&document.querySelector('.topbar').getBoundingClientRect().height>66)throw Error('Header too tall');if(innerWidth===390&&first&&first.getBoundingClientRect().bottom>844)throw Error('First complete card below fold '+first.getBoundingClientRect().bottom);if(innerWidth===390&&'${hash}'==='overview'&&rows[1].getBoundingClientRect().bottom>844)throw Error('First two quotes below fold '+rows[1].getBoundingClientRect().bottom);
const rgb=s=>(s.match(/[0-9.]+/g)||[]).map(Number),lum=c=>c.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);const samples=[];
for(const n of [...document.querySelectorAll('input[placeholder],button:disabled,.small-note,.catalog-summary,.lede,.metric-scope summary')].filter(n=>n.getClientRects().length&&getComputedStyle(n).visibility!=='hidden')){const style=getComputedStyle(n,n.matches('input[placeholder]')?'::placeholder':null);let p=n,bg;while(p){bg=rgb(getComputedStyle(p).backgroundColor);if(bg.length<4||bg[3]>.99)break;p=p.parentElement;}if(!p)continue;const a=lum(rgb(style.color)),b=lum(bg),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);if(ratio<4.5)throw Error('Placeholder/disabled/hint contrast '+ratio+' '+n.outerHTML.slice(0,100));if(n.matches('input[placeholder]')&&style.opacity!=='1')throw Error('Placeholder opacity');samples.push({type:n.matches('input')?'placeholder':n.disabled?'disabled':'hint',ratio});}
return {width:innerWidth,layout:document.body.dataset.layout,color:document.body.dataset.color,view:'${hash}',firstCardBottom:first?.getBoundingClientRect().bottom,secondQuoteBottom:'${hash}'==='overview'?rows[1].getBoundingClientRect().bottom:null,contrast:samples};})()`);results.push(observation);
const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,`compact-${layout}-${color}-${width}-${hash}.png`),Buffer.from(shot.data,'base64'));
}
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await navigate('library');
await send('Page.bringToFront');const key=async(k)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key:k,code:k,text:k==='Enter'?'\r':undefined,windowsVirtualKeyCode:k==='Tab'?9:k==='Escape'?27:13});await send('Input.dispatchKeyEvent',{type:'keyUp',key:k,code:k});await sleep(80);};
await evaluate(`document.querySelector('#library-tools .catalog-refine-open').focus()`);await key('Enter');assert(await evaluate(`document.getElementById('library-refine').open`),'Native filter opens');const drawerShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,'compact-filter-drawer-390.png'),Buffer.from(drawerShot.data,'base64'));for(let n=0;n<12;n++){await key('Tab');assert(await evaluate(`document.getElementById('library-refine').contains(document.activeElement)`),'Native modal contains focus');}await key('Escape');assert(await evaluate(`!document.getElementById('library-refine').open&&document.activeElement.classList.contains('catalog-refine-open')`),'ESC restores filter focus');
await evaluate(`document.querySelector('#library-tools .catalog-refine-open').click();document.getElementById('library-type').value='report';document.getElementById('library-type').dispatchEvent(new Event('change'));document.querySelector('#library-refine .catalog-refine-done').click()`);assert(await evaluate(`document.getElementById('library-active').textContent.includes('研究报告')`),'Filter chips visible');await evaluate(`document.getElementById('library-form').reset()`);await sleep(100);assert(await evaluate(`document.querySelectorAll('#library-results .catalog-card').length===JSON.parse(document.getElementById('catalog-data').textContent).records.length`),'Reset restores directory');
await evaluate(`document.getElementById('appearance-open').focus()`);await key('Enter');assert(await evaluate(`document.getElementById('appearance-settings').open`),'Native appearance opens');const settingsShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,'compact-appearance-popover-390.png'),Buffer.from(settingsShot.data,'base64'));await key('Tab');assert(await evaluate(`document.getElementById('appearance-settings').contains(document.activeElement)`),'Appearance contains focus');await key('Escape');assert(await evaluate(`document.activeElement.id==='appearance-open'`),'Appearance ESC restores focus');
await evaluate(`document.querySelector('.nav-toggle').focus()`);await key('Enter');await key('Escape');assert(await evaluate(`!document.querySelector('.sidebar').classList.contains('open')&&document.activeElement.classList.contains('nav-toggle')`),'Menu keyboard close');await evaluate(`location.hash='tasks'`);await sleep(80);await evaluate(`history.back()`);await sleep(100);assert(await evaluate(`!document.getElementById('library').hidden`),'Back restores library');
await evaluate(`document.getElementById('appearance-open').click()`);await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await sleep(100);const disabled=await evaluate(`(()=>{const n=document.getElementById('effects-choice');return {disabled:n.disabled,color:getComputedStyle(n).color,background:getComputedStyle(n).backgroundColor,opacity:getComputedStyle(n).opacity};})()`);assert(disabled.disabled&&disabled.opacity==='1');const rgb=s=>(s.match(/[0-9.]+/g)||[]).map(Number),lum=c=>c.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);const a=lum(rgb(disabled.color)),b=lum(rgb(disabled.background));disabled.contrast=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);assert(disabled.contrast>=4.5,'Disabled readable contrast');results.push({status:'PASS',keyboard:['catalog filter','appearance settings','menu','back','combination/reset'],disabled});
fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({status:'PASS',cases:48,first390Cards:results.filter(x=>x.width===390&&x.firstCardBottom).map(x=>({view:x.view,bottom:x.firstCardBottom,layout:x.layout,color:x.color})),first390Quotes:results.filter(x=>x.width===390&&x.view==='overview').map(x=>x.secondQuoteBottom)}));
}finally{if(ws){try{await send('Browser.close');}catch{}ws.close();}child.kill();}})().catch(err=>{console.error(err);process.exitCode=1;});
