/* Real local Chrome + built-in Node CDP client; no package install or external service. */
const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output','playwright');fs.mkdirSync(out,{recursive:true});
const chrome=process.env.CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-extensions','--no-first-run','--remote-debugging-address=127.0.0.1','--remote-debugging-port=9227',`--user-data-dir=${path.join(out,'cdp-profile-'+Date.now())}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let ws,seq=0;const pending=new Map();
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
async function connect(){for(let i=0;i<100;i++){try{const targets=await(await fetch('http://127.0.0.1:9227/json/list')).json();const target=targets.find(t=>t.type==='page');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});ws.onmessage=event=>{const m=JSON.parse(event.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}};return;}catch(err){await sleep(100);}}throw Error('Local Chrome CDP unavailable');}
async function navigate(hash){await send('Page.navigate',{url:pathToFileURL(path.join(root,'dist/dashboard/index.html')).href+'?viewport='+Date.now()+'#'+hash});await sleep(150);for(let i=0;i<100;i++){if(await evaluate("document.readyState==='complete' && !!document.getElementById('result-count')?.textContent"))return;await sleep(30);}throw Error('Dashboard initialization timed out');}
const smoke=async()=>{
 const checks=[],check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);},$=id=>document.getElementById(id),wait=()=>new Promise(r=>setTimeout(r,30));
 check('initial metrics',document.querySelectorAll('.metric').length===4&&document.querySelector('.metric b').textContent==='45');
 check('viewport overflow',document.documentElement.scrollWidth<=innerWidth);
 check('four exact amounts',document.querySelectorAll('.evidence-row').length===4 && document.querySelectorAll('.evidence-ledger .prohibited').length===1);
 const row=document.querySelector('[data-merchant="WStorm AI"]');row.focus();row.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));check('keyboard selects next supplier',document.querySelector('[data-merchant="gongsi.one"]').getAttribute('aria-pressed')==='true');
 if(innerWidth>1050){document.querySelector('[data-merchant="WStorm AI"]').click();check('selection updates inspector',document.getElementById('sku-inspector').textContent.includes('WStorm AI'));}
 else{document.querySelector('[data-merchant="WStorm AI"]').click();check('selection opens responsive sheet',document.getElementById('detail').open);document.getElementById('close-detail').click();await wait();check('focus restored to selected row',document.activeElement.dataset.merchant==='WStorm AI');}
 check('four rows visible at desktop first viewport',innerWidth<1051||document.querySelectorAll('.evidence-row')[3].getBoundingClientRect().bottom<innerHeight);
 check('Chinese labels/tags contained',[...document.querySelectorAll('#overview .tag')].every(n=>n.scrollWidth<=n.clientWidth+1));
 location.hash='quotes';await wait();check('quotes route',!$('quotes').hidden);
 const mobile=innerWidth<700;check('mobile card default',!mobile||!!document.querySelector('.quote-card'));
 if(mobile){$('open-filters').click();check('filter sheet', $('filters').classList.contains('open'));document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));check('filter ESC restores focus',!$('filters').classList.contains('open')&&document.activeElement===$('open-filters'));$('open-filters').click();}
 const set=(id,v)=>{$(id).value=v;$(id).dispatchEvent(new Event(id==='q'?'input':'change',{bubbles:true}));};
 set('tier','Plus');set('invoice','priced');set('q','ProPlus');check('combination filters',$('result-count').textContent.startsWith('1 条'));
 set('q','no-results-987654');check('empty results',!!document.querySelector('.reset-button'));document.querySelector('.reset-button').click();check('reset to 45',$('result-count').textContent.startsWith('45 条'));
 if(mobile)document.querySelector('#filters .mobile-close').click();
 $('card-view').click();check('card count',document.querySelectorAll('.quote-card').length===45);$('table-view').click();check('table count',document.querySelectorAll('.quote-table tbody tr').length===45);
 check('table overflow contained',document.documentElement.scrollWidth<=innerWidth);
 document.querySelector('.detail-button').click();check('drawer opens',$('detail').open);check('source links',[...document.querySelectorAll('.detail-sources a')].every(a=>a.href.startsWith('https:')));$('close-detail').click();check('drawer closes',!$('detail').open);
 location.hash='tutorial';await wait();check('tutorial route',!$('claude').hidden);location.hash='troubleshooting';await wait();check('troubleshooting route',!$('phone').hidden);
 if(mobile){document.querySelector('.nav-toggle').click();check('mobile nav drawer',document.querySelector('.sidebar').classList.contains('open'));document.querySelector('.sidebar .mobile-close').click();check('mobile nav closes',!document.querySelector('.sidebar').classList.contains('open'));document.querySelector('.nav-toggle').click();document.querySelector('[data-page="overview"]').click();await wait();check('navigation link closes sidebar',!document.querySelector('.sidebar').classList.contains('open'));history.back();await wait();check('browser back restores phone',!$('phone').hidden);}

 location.hash='routes';await wait();check('11 routes retained',document.querySelectorAll('#route-content .invoice-matrix tbody tr').length===11);check('route matrix initially open',document.querySelector('#route-content details').open);
 location.hash='claude';await wait();check('Claude first product distinction open',document.querySelector('#claude-content details:not(.quote-boundary)').open);
 location.hash='invoice-matrix';await wait();await wait();check('invoice matrix deep link opens',document.getElementById('invoice-matrix').open);check('nine candidates retained',document.querySelectorAll('#invoice-matrix tbody tr').length===9);
 location.hash='sources';await wait();$('source-search').value='no-source-987654';$('source-search').dispatchEvent(new Event('input'));check('source empty',!!$('reset-sources'));$('reset-sources').click();check('source reset',!!document.querySelector('.source-row'));

 location.hash='workbench';await wait();check('unified workbench route',!$('workbench').hidden);check('separate reviewed counts',document.querySelectorAll('.hub-stat').length===3&&Number(document.querySelector('.hub-stat b').textContent)===JSON.parse($('catalog-data').textContent).counts.artifacts);
 $('hub-query').value='第二轮';$('hub-search').requestSubmit();await wait();check('hub search opens catalogue',!$('library').hidden&&$('library-q').value==='第二轮');
 const setC=(id,v)=>{$(id).value=v;$(id).dispatchEvent(new Event(id.endsWith('-q')?'input':'change',{bubbles:true}));};
 setC('library-task','project-1');setC('library-type','report');setC('library-access','public');setC('library-from','2026-10-02');setC('library-to','2026-10-02');check('catalogue combined filters',document.querySelectorAll('#library-results .catalog-card').length===1&&$('library-count').textContent.startsWith('1 /'));
 const layout=$('layout-choice').value,color=document.body.dataset.color;$('layout-choice').value=layout==='A'?'B':'A';$('layout-choice').dispatchEvent(new Event('change'));check('catalogue state survives layout',$('library-q').value==='第二轮'&&$('library-task').value==='project-1'&&document.querySelectorAll('#library-results .catalog-card').length===1);$('layout-choice').value=layout;$('layout-choice').dispatchEvent(new Event('change'));if(layout==='B'&&document.body.dataset.color!==color)$('color-choice').click();
 setC('library-from','2026-10-03');check('invalid catalogue date feedback',!!$('library-date-error').textContent);$('library-form').reset();await wait();check('catalogue reset all',document.querySelectorAll('#library-results .catalog-card').length===JSON.parse($('catalog-data').textContent).records.length);
 setC('library-access','login');check('login has honest empty state',!!document.querySelector('.catalog-empty-reset'));document.querySelector('.catalog-empty-reset').click();await wait();setC('library-q','no-match-987654');check('catalogue empty and reset',!!document.querySelector('.catalog-empty-reset'));document.querySelector('.catalog-empty-reset').click();await wait();
 location.hash='websites';await wait();check('two actual website URLs',document.querySelectorAll('#websites-results .catalog-card').length===JSON.parse($('catalog-data').textContent).counts.websites&&[...document.querySelectorAll('#websites-results .button')].every(a=>a.href.startsWith('https://1337816143.github.io/')));check('unknown website updates retained',$('websites-results').textContent.includes('更新时间未记录'));setC('websites-from','2026-10-01');check('unknown updates excluded by date',!!document.querySelector('#websites-results .catalog-empty-reset'));$('websites-form').reset();await wait();
 location.hash='tasks';await wait();check('exact approved project snapshots',document.querySelectorAll('#tasks-results .task-card').length===JSON.parse($('catalog-data').textContent).tasks.length);setC('tasks-task','project-1');check('task-specific progress',document.querySelectorAll('#tasks-results .task-card').length===1&&$('tasks-results').textContent.includes('AI上游调研'));document.querySelector('#tasks-results details').open=true;check('four original subtask gaps retained',document.querySelectorAll('.task-child').length===4);$('tasks-form').reset();await wait();
 if(mobile){location.hash='quotes';await wait();const nav=document.querySelector('.module-nav');check('single research tab row, all modules accessible',nav.querySelectorAll('a').length===5&&nav.getBoundingClientRect().height<=48&&[...nav.querySelectorAll('a')].every(a=>a.scrollWidth<=a.clientWidth+1)&&getComputedStyle(document.querySelector('.workspace-nav')).display==='none');}
 check('catalogue viewport overflow',document.documentElement.scrollWidth<=innerWidth);
 return {status:'PASS',width:innerWidth,checks};
};
(async()=>{try{
 await connect();await send('Page.enable');const results=[];await navigate('');assert(await evaluate("!document.getElementById('workbench').hidden"),'Fresh default unified workbench');assert.equal(await evaluate('document.body.dataset.layout'), 'B');assert.equal(await evaluate('document.body.dataset.color'),'dark');assert(await evaluate("!document.querySelector('.sidebar').classList.contains('open')"),'Fresh profile default menu closed');
 for(const width of [1440,1280,390,768]){await send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:width<700});await navigate('overview');const result=await evaluate(`(${smoke.toString()})()`);assert(result&&result.status==='PASS','Browser smoke failed');assert.equal(result.width,width);results.push(result);console.log(JSON.stringify(result));}

 // Layout and palette are independent and never rebuild the research state.
 await send('Emulation.setDeviceMetricsOverride',{width:1280,height:1100,deviceScaleFactor:1,mobile:false});await navigate('quotes');
 const appearanceState=await evaluate(`(() => {const q=document.getElementById('q');q.value='ProPlus';q.dispatchEvent(new Event('input',{bubbles:true}));const before=document.getElementById('result-count').textContent;document.getElementById('color-choice').click();if(document.body.dataset.layout!=='B'||document.body.dataset.color!=='light')throw Error('B light must retain B layout');document.getElementById('layout-choice').value='A';document.getElementById('layout-choice').dispatchEvent(new Event('change'));if(document.body.dataset.color!=='light'||!document.getElementById('color-choice').hidden)throw Error('A is explicit light layout');document.getElementById('layout-choice').value='B';document.getElementById('layout-choice').dispatchEvent(new Event('change'));if(document.body.dataset.color!=='light'||document.getElementById('result-count').textContent!==before||q.value!=='ProPlus')throw Error('Appearance lost filters');return true;})()`);assert(appearanceState);
 await navigate('overview');assert.equal(await evaluate('document.body.dataset.color'),'light','Saved B light survives reload');
 for(const width of [1280,390])for(const [layout,color] of [['B','dark'],['B','light'],['A','light']]){
   await send('Emulation.setDeviceMetricsOverride',{width,height:1100,deviceScaleFactor:1,mobile:width<700});await navigate('overview');
   await evaluate(`(() => {const select=document.getElementById('layout-choice');select.value='${layout}';select.dispatchEvent(new Event('change'));if('${layout}'==='B'&&document.body.dataset.color!=='${color}')document.getElementById('color-choice').click();})()`);await evaluate('window.scrollTo(0,0)');await sleep(80);
   assert(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Appearance overflow');
   const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,`v16-${layout}-${color}-${width}.png`),Buffer.from(shot.data,'base64'));
 }
 await evaluate(`document.getElementById('layout-choice').value='B';document.getElementById('layout-choice').dispatchEvent(new Event('change'));if(document.body.dataset.color!=='dark')document.getElementById('color-choice').click()`);
 results.push({status:'PASS',checks:['B dark / B light / A light','filter preserved across appearance','local appearance persists reload','six real appearance screenshots','appearance overflow']});
 const key=async(k,code=k,modifiers=0)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key:k,code,modifiers,text:k==='Enter'?'\r':undefined,windowsVirtualKeyCode:k==='Tab'?9:k==='Escape'?27:k==='Enter'?13:0});await send('Input.dispatchKeyEvent',{type:'keyUp',key:k,code,modifiers});await sleep(40);};
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await navigate('overview');
 await send('Page.bringToFront');
 await evaluate(`document.getElementById('appearance-open').click();document.getElementById('color-choice').focus()`);const beforeColor=await evaluate('document.body.dataset.color');await key('Enter');assert.notEqual(await evaluate('document.body.dataset.color'),beforeColor,'Native keyboard theme toggle');await key('Enter');await evaluate(`document.getElementById('appearance-settings').close()`);
 await evaluate(`document.querySelector('[data-merchant="WStorm AI"]').click();document.getElementById('close-detail').click();const select=document.getElementById('layout-choice');select.value='A';select.dispatchEvent(new Event('change'));select.value='B';select.dispatchEvent(new Event('change'))`);assert(await evaluate(`document.querySelector('[data-merchant="WStorm AI"]').getAttribute('aria-pressed')==='true'`),'Selected supplier retained across layouts');
 await evaluate("document.querySelector('[data-merchant=\"WStorm AI\"]').focus()");await key('Enter');assert(await evaluate("document.getElementById('detail').open"),'Native keyboard Enter opens candidate');await key('Escape');assert(await evaluate("!document.getElementById('detail').open && document.activeElement.dataset.merchant==='WStorm AI'"),'Native ESC returns candidate focus');
 await evaluate("location.hash='quotes'");await sleep(100);await evaluate("document.getElementById('open-filters').click()");
 for(let n=0;n<14;n++){await key('Tab');assert(await evaluate("document.getElementById('filters').contains(document.activeElement)"),'Filter focus remains inside sheet');}
 await key('Tab','Tab',8);assert(await evaluate("document.getElementById('filters').contains(document.activeElement)"),'Reverse Tab remains in sheet');await key('Escape');assert(await evaluate("!document.getElementById('filters').classList.contains('open') && document.activeElement.id==='open-filters'"),'ESC filter focus');
 await evaluate("document.querySelector('.nav-toggle').click()");for(let n=0;n<12;n++){await key('Tab');assert(await evaluate("document.querySelector('.sidebar').contains(document.activeElement)"),'Navigation focus contained');}await key('Escape');assert(await evaluate("!document.querySelector('.sidebar').classList.contains('open') && document.activeElement.classList.contains('nav-toggle')"),'Native nav ESC restores focus');
 await evaluate("location.hash='overview'");await sleep(60);await evaluate("location.hash='quotes'");await sleep(60);await evaluate("document.querySelector('.detail-button').focus()");await key('Enter');assert(await evaluate("document.getElementById('detail').open"),'SKU keyboard Enter');await evaluate('history.back()');await sleep(150);assert(await evaluate("!document.getElementById('detail').open && !document.getElementById('overview').hidden"),'Browser back closes sheet and returns overview');
 results.push({status:'PASS',width:390,checks:['fresh profile default B dark / menu closed','native theme toggle Enter','selected supplier survives layout','native keyboard Enter','native ESC candidate focus','14 Tab steps confined','reverse Tab confined','filter ESC restores focus','navigation Tab confined','navigation ESC focus','browser back closes SKU sheet']});
 for(const [name,width,height,hash] of [['desktop-routes',1280,1100,'routes'],['mobile-routes',390,1000,'routes'],['desktop-phone',1280,1000,'phone'],['mobile-phone',390,1000,'phone'],['desktop-claude',1280,1100,'claude'],['mobile-claude',390,1000,'claude'],['desktop-timeline',1280,1100,'timeline'],['mobile-timeline',390,1000,'timeline'],['desktop-sources',1280,1000,'sources'],['mobile-sources',390,1000,'sources'],['desktop-1440',1440,1000,'overview'],['tablet-overview',768,1000,'overview'],['desktop-overview',1280,1100,'overview'],['desktop-quotes',1280,1200,'quotes'],['mobile-overview',390,1000,'overview'],['mobile-quotes',390,1100,'quotes']]){
   await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700});await navigate(hash);await evaluate('window.scrollTo(0,0)');await sleep(100);const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(shot.data,'base64'));
 }
 for(const [name,expression] of [['mobile-navigation',"document.querySelector('.nav-toggle').click()"],['mobile-filter-sheet',"document.getElementById('open-filters').click()"],['mobile-detail-drawer',"document.querySelector('.detail-button').click()"],['mobile-quote-cards',"document.getElementById('result-count').scrollIntoView({behavior:'instant'})"],['mobile-empty-results',"document.getElementById('q').value='no-match-987654';document.getElementById('q').dispatchEvent(new Event('input'));document.getElementById('result-count').scrollIntoView({behavior:'instant'})"]]){
   await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await navigate('quotes');await evaluate('window.scrollTo(0,0)');await evaluate(expression);await sleep(100);const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(shot.data,'base64'));
 }

 // Three appearances, all seven modules, fresh navigations and real screenshots.
 const appearanceResults=[];
 for(const width of [1280,390])for(const [layout,color] of [['B','dark'],['B','light'],['A','light']])for(const hash of ['workbench','library','websites','tasks','overview','quotes','routes','phone','claude','timeline','sources']){
   await send('Emulation.setDeviceMetricsOverride',{width,height:1100,deviceScaleFactor:1,mobile:width<700});await evaluate(`localStorage.clear()`);await navigate(hash);
   await evaluate(`(() => {const select=document.getElementById('layout-choice');select.value='${layout}';select.dispatchEvent(new Event('change'));if('${layout}'==='B'&&document.body.dataset.color!=='${color}')document.getElementById('color-choice').click();window.scrollTo(0,0);})()`);await sleep(60);
   const observations=await evaluate(`(() => {
     if(document.documentElement.scrollWidth>innerWidth)throw Error('Appearance module overflow');
     if(innerWidth<700&&(document.querySelector('.sidebar').classList.contains('open')||getComputedStyle(document.querySelector('.sidebar')).visibility!=='hidden'))throw Error('Mobile nav obscures initial page');
     if(innerWidth>1050&&document.body.dataset.layout==='A'&&document.querySelectorAll('.evidence-row')[3].getBoundingClientRect().bottom>innerHeight)throw Error('A four compact rows must fit first viewport');
     const rgb=s=>(s.match(/[0-9.]+/g)||[]).map(Number),l=c=>c.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);
     const samples=[];for(const n of [...document.querySelectorAll('a,button,label,input,select,.unknown,.prohibited,.prose,.small-note')].filter(n=>n.getClientRects().length&&n.textContent.trim()).slice(0,180)){
       const style=getComputedStyle(n);let p=n,bg;while(p){bg=rgb(getComputedStyle(p).backgroundColor);if(bg.length<4||bg[3]>.99)break;p=p.parentElement;}
       if(!p)continue;const a=l(rgb(style.color)),b=l(bg),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05),large=parseFloat(style.fontSize)>=24||(parseFloat(style.fontSize)>=18.66&&parseInt(style.fontWeight)>=700);if(ratio<(large?3:4.5)-.01)throw Error('Contrast '+ratio.toFixed(2)+' '+document.body.dataset.layout+'/'+document.body.dataset.color+' '+n.className+' '+n.textContent.slice(0,35)+' color='+style.color+' bg='+bg+' parent='+p.className);samples.push(ratio);
     }
     return {layout:document.body.dataset.layout,color:document.body.dataset.color,width:innerWidth,contrastSamples:samples.length,minContrast:Math.min(...samples)};
   })()`);appearanceResults.push({...observations,module:hash});
   const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,`v16-${layout}-${color}-${width}-${hash}.png`),Buffer.from(shot.data,'base64'));
 }
 results.push({status:'PASS',checks:['66 actual module / appearance screenshots','mobile default nav hidden in all appearances','A four compact rows visible','actual computed text contrast WCAG AA'],appearances:appearanceResults});
 // Outside click and appearance changes close navigation; selection remains intact.
 await navigate('overview');await evaluate(`document.querySelector('.nav-toggle').click();document.querySelector('.nav-backdrop').click()`);assert(await evaluate("!document.querySelector('.sidebar').classList.contains('open')"),'Outside click closes nav');
 await evaluate(`document.querySelector('.nav-toggle').click();document.getElementById('layout-choice').value='B';document.getElementById('layout-choice').dispatchEvent(new Event('change'));`);assert(await evaluate("!document.querySelector('.sidebar').classList.contains('open')"),'Appearance closes responsive nav');

 for(const [layout,color] of [['B','dark'],['B','light'],['A','light']]){
   await evaluate(`localStorage.setItem('mydotwork-appearance',JSON.stringify({layout:'${layout}',color:'${color}'}))`);await navigate('quotes');await send('Page.bringToFront');
   await evaluate(`document.querySelector('.nav-toggle').focus()`);await key('Enter');assert(await evaluate(`document.querySelector('.sidebar').classList.contains('open')`),'Appearance native nav Enter');await key('Tab');assert(await evaluate(`document.querySelector('.sidebar').contains(document.activeElement)`),'Appearance native nav Tab '+await evaluate('document.activeElement.outerHTML')); await key('Escape');assert(await evaluate(`document.activeElement.classList.contains('nav-toggle')`),'Appearance native nav Escape focus');
   await evaluate(`document.getElementById('open-filters').focus()`);await key('Enter');assert(await evaluate(`document.getElementById('filters').classList.contains('open')`),'Appearance native filter Enter');await key('Tab');assert(await evaluate(`document.getElementById('filters').contains(document.activeElement)`),'Appearance native filter Tab');await key('Escape');assert(await evaluate(`document.activeElement.id==='open-filters'`),'Appearance filter Escape focus');
 }
 results.push({status:'PASS',checks:['B dark / B light / A light native Enter, Tab and Escape for navigation and filters']});
 await navigate('workbench');await send('Page.bringToFront');await evaluate(`document.getElementById('hub-query').value='第二轮';document.getElementById('hub-query').focus()`);await key('Enter');assert(await evaluate(`!document.getElementById('library').hidden && document.getElementById('library-q').value==='第二轮'`),'Native Enter hub search');
 await evaluate(`document.querySelector('#library-form button[type="reset"]').focus()`);await key('Enter');assert(await evaluate(`document.getElementById('library-q').value===''&&document.querySelectorAll('#library-results .catalog-card').length===JSON.parse(document.getElementById('catalog-data').textContent).records.length`),'Native Enter catalogue reset');
 await navigate('tasks');await evaluate(`document.querySelector('#tasks-results summary').focus()`);await key('Enter');assert(await evaluate(`document.querySelector('#tasks-results details').open`),'Native Enter task disclosure');
 await navigate('workbench');await evaluate(`document.querySelector('[data-task-id="project-5"]').click()`);await sleep(60);assert(await evaluate(`!document.getElementById('tasks').hidden && document.getElementById('tasks-task').value==='project-5' && document.querySelectorAll('#tasks-results .task-card').length===1`),'Hub project continues specific task');
 results.push({status:'PASS',checks:['native Enter catalogue search and reset','native Enter task scope disclosure','hub project continues its task']});

 await navigate('workbench');await evaluate(`document.getElementById('appearance-open').click()`);assert(await evaluate('WorkbenchBoot.beforeBody'),'Preferences restored before body');assert(await evaluate("document.getElementById('appearance-state').textContent.includes(document.body.dataset.layout)"),'Visible appearance label');assert(await evaluate("document.querySelector('.ui-version').textContent.includes('v1.6.0')"),'Visible UI version');
 await evaluate("document.getElementById('effects-choice').click()");assert(await evaluate("document.documentElement.dataset.glass==='solid'"),'Solid fallback control');await navigate('workbench');await evaluate(`document.getElementById('appearance-open').click()`);assert(await evaluate("document.documentElement.dataset.glass==='solid'"),'Solid fallback persists reload');
 await evaluate("document.getElementById('effects-choice').click()");await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await sleep(100);assert(await evaluate("document.documentElement.dataset.glass==='solid'"),'Reduced motion disables glass');assert(await evaluate("document.getElementById('effects-choice').disabled"),'Reduced motion preference respected');
 const fallbackShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,'v16-reduced-motion-solid-390.png'),Buffer.from(fallbackShot.data,'base64'));await send('Emulation.setEmulatedMedia',{features:[]});
 results.push({status:'PASS',checks:['pre-body preference restoration','visible version and appearance','solid control persists','reduced motion fallback and screenshot']});
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(results,null,2));console.log('PASS: actual 1440/1280/390/768px Chrome viewports, all modules in three appearances, computed contrast, and actual screenshots');
 }catch(error){const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,'glass-debug.png'),Buffer.from(shot.data,'base64'));throw error;}finally{if(ws){try{await send('Browser.close');}catch(err){}ws.close();}child.kill();}})().catch(err=>{console.error(err);process.exitCode=1;});
