const assert = require('node:assert/strict');
const fs = require('node:fs');
const M = require('../src/dashboard.js');
const d = JSON.parse(fs.readFileSync('dist/dashboard/data.json','utf8'));
const defaults = {q:'',tier:'',basis:'display',invoice:'',risk:'',resale:'',agency:'',sort:'price'};
assert.equal(d.records.length,45);
assert.equal(new Set(d.records.map(M.merchantName)).size,22);
assert.equal(d.invoice.prior_candidates.length+d.invoice.new_candidates.length,9);
assert.equal(d.routes.routes.length,11);
assert.equal(d.historyCount,126);
assert.equal(new Set(d.records.map(r=>r.id)).size,45);
assert.equal(M.filter(d.records,{...defaults,q:'not-a-merchant-987654'}).length,0);
assert.equal(M.filter(d.records,defaults).length,45);
const combination={...defaults,tier:'Plus',invoice:'priced',resale:'not-prohibited',q:'ProPlus'};
assert.deepEqual(M.filter(d.records,combination).map(r=>r.id),['proplus-plus']);
assert(M.filter(d.records,{...defaults,risk:'high'}).every(M.isHigh));
assert(M.filter(d.records,{...defaults,invoice:'unknown'}).every(r=>r.invoice_supported_claim==null));
assert(M.filter(d.records,{...defaults,agency:'no-upfront'}).every(r=>r.minimum_quantity===1));
const zy=d.records.find(r=>r.id==='zy-plus'),cat=d.records.find(r=>r.id==='cat-plus');
assert.equal(M.amount(zy,'preview'),null,'USDT may not enter CNY payment-preview ranking');
assert.equal(M.amount(cat,'preview'),110.95);
assert.equal(M.amount(d.records.find(r=>r.id==='fan-plus'),'display'),null);
assert.equal(M.compare({...cat,id:'known',display_price:10},{...cat,id:'unknown',display_price:null},defaults),-1);
assert.equal(M.compare({...cat,id:'unknown',display_price:null},{...cat,id:'known',display_price:10},defaults),1);
const groups=M.groups(d.records,defaults);
assert.equal(groups.reduce((n,g)=>n+g.rows.length,0),45);
assert(groups.every(g=>new Set(g.rows.map(r=>r.sku_group)).size===1));
assert(groups.every(g=>new Set(g.rows.map(r=>r.display_currency)).size===1));
assert(groups.every(g=>new Set(g.rows.map(r=>r.payment_group)).size===1));
assert.notEqual(M.groupKey(d.records.find(r=>r.id==='hansen-pro200'),defaults.basis),M.groupKey(d.records.find(r=>r.id==='hansen-pro200-renew'),defaults.basis));
assert.equal(M.esc('<script>"&'),'&lt;script&gt;&quot;&amp;');
assert(d.records.filter(r=>r.merchant==='贝果科技').every(r=>r.resale==='标准条款禁止转售'));
assert(!d.records.find(r=>r.id==='maimen-pro200-invoice').tier.includes('past-20x'));
assert(d.records.every(r=>r.source_urls.length && r.source_urls.every(s=>/^https?:\/\//.test(s))));
assert(d.sources.every(s=>/^https?:\/\//.test(s)));
assert(!JSON.stringify(d).includes('messages'));
console.log('PASS: counts, combination filters, empty/reset model, SKU/renewal/currency groups, null sorting, USDT exclusion, corrections, public sources, escaping');
