const assert=require('node:assert/strict'),fs=require('node:fs');
const S=require('../src/status.js'),A=require('../src/archive.js');
const data=JSON.parse(fs.readFileSync('dist/dashboard/catalog.json','utf8'));
const items=data.statusSnapshot.items;
assert.equal(items.length,7);assert.equal(S.filter(items).length,7);
assert.deepEqual(S.counts(items),{running:4,waiting:3,blocked:0,round_complete:0});
assert.deepEqual(S.filter(items,'waiting').map(x=>x.number),[3,4,5]);
assert.equal(S.filter(items,'blocked').length,0,'No fake blocked task to fill a UI state');
assert.equal(items.find(x=>x.number===7).state,'running');
assert(items.find(x=>x.number===7).publication.includes('已发布'));
assert(items.find(x=>x.number===7).completion.includes('未完成'),'Publication must not infer complete requirements');
const base={id:'test',role:'user',time:'2026-10-03T09:00:00Z',text:'Paper 论文；FarmSystemDesign 海南地图'};
assert(A.matches(base,{q:'paper 论文',role:'user',from:'2026-10-03',to:'2026-10-03',project:'paper'}));
for(const s of [{q:'paper missing'},{role:'assistant'},{from:'2026-10-04'},{to:'2026-10-02'},{project:'income'}])assert(!A.matches(base,s));
assert(A.matches(base,{project:'farm'}));
assert(A.matches({...base,time:'2026-10-02T23:30:00-05:00'},{from:'2026-10-03',to:'2026-10-03'}),'Date filters normalize offsets to UTC');
assert(!A.matches({...base,time:'unknown'},{from:'2026-10-03'}),'Unknown dates do not pass a date range');
assert(A.matches({...base,text:''},{}),'Empty visible messages remain available');
assert(!A.matches({...base,text:''},{project:'paper'}));
const chat=JSON.parse(fs.readFileSync('data/dot-chat.json','utf8'));
assert.equal(chat.messages.length,434);assert.equal(chat.messages.filter(x=>x.text).length,424);
assert.equal(chat.messages.filter(m=>A.matches(m,{from:'2026-10-03',to:'2026-10-03'})).length,79,'UTC date filter separates newly read messages');
assert.equal(chat.coverage.readApiHistoryExhausted,false);
console.log('PASS: snapshot states, publication/completion separation, empty status, date/project/role/AND searches and preserved empty messages');
