const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../src/catalog.js'),root=path.resolve(__dirname,'..');
const d=JSON.parse(fs.readFileSync(path.join(root,'dist/dashboard/catalog.json'),'utf8'));
assert.equal(d.records.length,d.counts.artifacts+d.counts.websites+d.counts.tasks);
assert.equal(new Set(d.records.map(r=>r.id)).size,d.records.length);
assert(d.records.every(r=>r.metadataApproved===true&&r.access==='public'));
const reports=C.filter(d.records,{task:'project-1',type:'report',access:'public',q:'第二轮',from:'2026-10-02',to:'2026-10-02'},d.tasks);
assert.deepEqual(reports.map(r=>r.id),['upstream-round2']);
assert.equal(C.filter(d.records,{q:'no-match-987654'},d.tasks).length,0);
assert.equal(C.filter(d.records,{access:'login'},d.tasks).length,0);
assert.equal(C.filter(d.records,{},d.tasks).length,d.records.length);
const sites=d.records.filter(r=>['mydotwork-workbench','evolution-mirror'].includes(r.id));
const datedSites=d.records.filter(r=>['paper-learning-site','farm-system-site'].includes(r.id));
assert.equal(datedSites.length,2);assert(datedSites.every(r=>r.updatedAt==='2026-10-03'));
assert.equal(C.filter(datedSites,{from:'2026-10-03',to:'2026-10-03'},d.tasks).length,2);
assert.equal(C.filter(datedSites,{to:'2026-10-02'},d.tasks).length,0);
assert(sites.every(r=>r.updatedAt===null));
assert.equal(C.filter(sites,{from:'2026-10-01'},d.tasks).length,0,'Unknown dates are excluded by date filters');
assert(C.filter(d.records,{sort:'latest'},d.tasks).slice(-sites.length).every(r=>r.updatedAt===null));
assert(C.filter(d.records,{sort:'oldest'},d.tasks).slice(-sites.length).every(r=>r.updatedAt===null));
assert.equal(C.filter([{...reports[0],metadataApproved:false}],{},d.tasks).length,0);
assert.equal(C.filter([{...reports[0],access:'private'}],{},d.tasks).length,0);
assert.deepEqual(C.filter(d.records,{q:'上游 JSON',type:'dataset'},d.tasks).map(r=>r.id).sort(),['round1-data','round2-data','upstream-round3-7-data'],'Search uses approved project titles with AND terms');
assert.deepEqual(C.filter(d.records,{task:'project-17',type:'report'},d.tasks).map(r=>r.id),['side-income-report'],'Side-income report has its own project, not the agricultural project');
assert.equal(C.stamp(null),null);assert.equal(C.stamp('unknown'),null);
console.log('PASS: catalogue counts, explicit public metadata, task/type/access/date/search combinations, reset/empty, unknown-date sorting and no unapproved records');
